name: Model CI
on: [push, pull_request]

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11
      
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      
      - name: Install CML
        run: npm install -g @dvcorg/cml
      
      - name: Install Python dependencies & Google Cloud CLI
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install -r requirements.txt
          sudo apt-get update
          sudo apt-get install -y google-cloud-cli
      
      - name: Setup GCS credentials
        run: echo '${{ secrets.GCPKEY }}' > key.json
      
      - name: Configure DVC remote
        run: |
          echo "Current DVC config:"
          cat .dvc/config || echo "No .dvc/config found"
          echo "Setting up remote..."
          dvc remote add -df gcs-remote gs://mlops-course-soy-bridge-474214-h8-unique
          dvc remote default gcs-remote
          echo "Updated DVC config:"
          cat .dvc/config
          echo "DVC remote list:"
          dvc remote list
      
      - name: Pull DVC data
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ github.workspace }}/key.json
        run: |
          echo "Pulling data from DVC..."
          dvc pull -v || echo "DVC pull failed"
      
      - name: Run tests & generate report
        run: pytest --md report.md
      
      - name: Create CML report (PRs only)
        if: github.event_name == 'pull_request'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: cml comment create report.md
